// <auto-generated />
using System;
using DVLD_E_Enfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVLD_E_Enfrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DVLD_Domain.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeID");

                    b.HasIndex("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("DVLD_Domain.Models.ApplicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("ApplicationTypes");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("LocalDrivingLicenseApplicationID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalDrivingLicenseApplicationID");

                    b.HasIndex("TestTypeID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DVLD_Domain.Models.DetainedLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<int>("LicenseID")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReleasedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseID");

                    b.HasIndex("ReleaseApplicationID");

                    b.HasIndex("ReleasedByUserID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("DetainedLicenses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DVLD_Domain.Models.InternationalLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssuedUsingLocalLicenseID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("DriverID");

                    b.HasIndex("IssuedUsingLocalLicenseID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("InternationalLicenses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssueReason")
                        .HasColumnType("int");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("DriverID");

                    b.HasIndex("LicenseClassID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LicenseClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ClassFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DefaultValidityLength")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("MinimumAllowedAge")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("LicenseClasses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LocalDrivingLicenseApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.Property<int>("NumberofPassedTests")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("LicenseClassID");

                    b.ToTable("LocalDrivingLicenseApplications");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NationalityCountryID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalNo")
                        .IsUnique();

                    b.HasIndex("NationalityCountryID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Test", b =>
                {
                    b.Property<int>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("TestResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("AppointmentID");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("DVLD_Domain.Models.TestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("createdbyuserid");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("DVLD_Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("createdbyuserid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DVLD_Domain.Models.UserLoginAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userUserLoginAudits");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Application", b =>
                {
                    b.HasOne("DVLD_Domain.Models.ApplicationType", "ApplicationType")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.Person", "Person")
                        .WithMany("Applications")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Person");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.ApplicationType", b =>
                {
                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Appointment", b =>
                {
                    b.HasOne("DVLD_Domain.Models.LocalDrivingLicenseApplication", "LocalDrivingLicenseApplication")
                        .WithMany("Appointments")
                        .HasForeignKey("LocalDrivingLicenseApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.TestType", "TestType")
                        .WithMany("Appointments")
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("LocalDrivingLicenseApplication");

                    b.Navigation("TestType");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.DetainedLicense", b =>
                {
                    b.HasOne("DVLD_Domain.Models.License", "License")
                        .WithMany("DetainedLicenses")
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.Application", "ReleaseApplication")
                        .WithMany()
                        .HasForeignKey("ReleaseApplicationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "ReleasedByUser")
                        .WithMany()
                        .HasForeignKey("ReleasedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("License");

                    b.Navigation("ReleaseApplication");

                    b.Navigation("ReleasedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Driver", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Person", "Person")
                        .WithOne("Driver")
                        .HasForeignKey("DVLD_Domain.Models.Driver", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DVLD_Domain.Models.InternationalLicense", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Application", "Application")
                        .WithOne("InternationalLicense")
                        .HasForeignKey("DVLD_Domain.Models.InternationalLicense", "ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.Driver", "Driver")
                        .WithMany("InternationalLicenses")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.License", "LocalLicense")
                        .WithMany()
                        .HasForeignKey("IssuedUsingLocalLicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");

                    b.Navigation("LocalLicense");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.License", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Application", "Application")
                        .WithOne("License")
                        .HasForeignKey("DVLD_Domain.Models.License", "ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.Driver", "Driver")
                        .WithMany("Licenses")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.LicenseClass", "LicenseClass")
                        .WithMany("Licenses")
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");

                    b.Navigation("LicenseClass");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LicenseClass", b =>
                {
                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LocalDrivingLicenseApplication", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Application", "Application")
                        .WithOne("LocalDrivingLicenseApplication")
                        .HasForeignKey("DVLD_Domain.Models.LocalDrivingLicenseApplication", "ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.LicenseClass", "LicenseClass")
                        .WithMany("LocalDrivingLicenseApplications")
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("LicenseClass");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Person", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Country", "NationalityCountry")
                        .WithMany("People")
                        .HasForeignKey("NationalityCountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("NationalityCountry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Test", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Appointment", "Appointment")
                        .WithOne("Test")
                        .HasForeignKey("DVLD_Domain.Models.Test", "AppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.TestType", b =>
                {
                    b.HasOne("DVLD_Domain.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD_Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdbyuserid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DVLD_Domain.Models.User", b =>
                {
                    b.HasOne("DVLD_Domain.Models.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("DVLD_Domain.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DVLD_Domain.Models.UserLoginAudit", b =>
                {
                    b.HasOne("DVLD_Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Application", b =>
                {
                    b.Navigation("InternationalLicense")
                        .IsRequired();

                    b.Navigation("License")
                        .IsRequired();

                    b.Navigation("LocalDrivingLicenseApplication")
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD_Domain.Models.ApplicationType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Appointment", b =>
                {
                    b.Navigation("Test")
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD_Domain.Models.Country", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Driver", b =>
                {
                    b.Navigation("InternationalLicenses");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.License", b =>
                {
                    b.Navigation("DetainedLicenses");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LicenseClass", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("LocalDrivingLicenseApplications");
                });

            modelBuilder.Entity("DVLD_Domain.Models.LocalDrivingLicenseApplication", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DVLD_Domain.Models.Person", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD_Domain.Models.TestType", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
